DROP VIEW IF EXISTS VW_TOKEN;
DROP VIEW IF EXISTS VW_USUARIO;

DROP TRIGGER IF EXISTS TR_CONTATO_INSERT;
DROP TRIGGER IF EXISTS TR_HISTORICO_ACESSO_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_REGISTRO_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_UPDATE;
DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_USUARIO_UPDATE;
DROP TRIGGER IF EXISTS TR_USUARIO_INSERT;

DROP TABLE IF EXISTS ARQUIVO;
DROP TABLE IF EXISTS PROCESSO_CAMPANHA;
DROP TABLE IF EXISTS RELATORIO;
DROP TABLE IF EXISTS ITEM_FATURA;
DROP TABLE IF EXISTS FATURA;
DROP TABLE IF EXISTS CAMPANHA;
DROP TABLE IF EXISTS EMPRESA_USUARIO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS PLANO;
DROP TABLE IF EXISTS PROCESSO;

DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS HISTORICO_ACESSO;
DROP TABLE IF EXISTS ATALHO;
DROP TABLE IF EXISTS REGISTRO;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS USUARIO;



/* Criando a tabela de contatos do sites*/
CREATE TABLE CONTATO (
	IDCONTATO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL
    , TELEFONE VARCHAR(30) NOT NULL
    , MENSAGEM TEXT
    , TIPO VARCHAR(30) NOT NULL
    , VISUALIZADO CHAR(1) NULL	-- INDICA SE O CONTATO FOI VISUALIZADO
    , RESPONDIDO CHAR(1) NULL	-- INDICA QUE SE ENTRAMOS EM CONTATO COM O SOLICITANTE
    , INTERESSE CHAR(1) NULL	-- INDICA QUE O CLIENTE ESTA INTERESSADO
    , CLIENTE CHAR(1) NULL		-- INDICA QUE O CONTATO VIROU UM CLIENTE
    , ATIVO CHAR(1) NULL		-- INDICA QUE O CONTATO AINDA ESTA ATIVO EM CONTATO
    , DT_CONTATO DATETIME NULL
    , CONSTRAINT PK_CONTATO PRIMARY KEY (IDCONTATO)
);

/* Criando a tabela de usuarios*/
CREATE TABLE USUARIO (
	IDUSUARIO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL UNIQUE
    , SENHA VARCHAR(200) NOT NULL
    , ATIVO CHAR(1) NOT NULL
    , DT_ATIVACAO DATETIME
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_CADASTRO DATETIME NOT NULL
    , DT_ATUALIZADO DATETIME NOT NULL
    , TIPO VARCHAR(15) NOT NULL
    , CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO)
);

/* Criando a tabela de usuarios*/
CREATE TABLE TOKEN (
    IDTOKEN INT IDENTITY(1,1) NOT NULL
	, IDUSUARIO INT NOT NULL
    , TOKEN VARCHAR(200) NOT NULL
    , SECRET_KEY VARCHAR(200) NOT NULL
    , DT_CRIACAO DATETIME NOT NULL
    , DT_EXPIRACAO DATETIME NOT NULL
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_ATUALIZADO DATETIME NOT NULL
    , CONSTRAINT PK_TOKEN PRIMARY KEY (IDTOKEN)
    , CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE REGISTRO (
    IDREGISTRO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT NOT NULL
    , IDTOKEN INT
    , MODULO VARCHAR(200) NOT NULL
    , ACAO VARCHAR(200) NOT NULL
    , DT_REGISTRO DATETIME NOT NULL
    , CONSTRAINT PK_REGISTRO PRIMARY KEY (IDREGISTRO)
    , CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_REGISTRO_TOKEN FOREIGN KEY (IDTOKEN) REFERENCES TOKEN(IDTOKEN)
);

CREATE TABLE HISTORICO_ACESSO (
    IDHISTORICO_ACESSO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT
    , ROTA VARCHAR(250) NOT NULL
    , DT_ACESSO DATETIME NOT NULL
    , CONSTRAINT PK_HISTORICO_ACESSO PRIMARY KEY (IDHISTORICO_ACESSO)
    , CONSTRAINT FK_HISTORICO_ACESSO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE ATALHO (
    IDATALHO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT NOT NULL
    , GRUPO VARCHAR(100) NOT NULL
    , NOME VARCHAR(100) NOT NULL
    , ROTA VARCHAR(250) NOT NULL
    , CONSTRAINT PK_ATALHO PRIMARY KEY (IDATALHO)
    , CONSTRAINT FK_ATALHO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE PLANO (
    IDPLANO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(100) NOT NULL
    , DESCRICAO VARCHAR(300) NOT NULL
    , PARCEIRO_GROWTH CHAR(1) NOT NULL
    , VALOR DECIMAL(8,2)
    , STATUS CHAR(1) NOT NULL
	, DT_INICIAL_VIGENCIA DATETIME
	, DT_FINAL_VIGENCIA DATETIME
    , CONSTRAINT PK_PLANO PRIMARY KEY (IDPLANO)
);

CREATE TABLE PROCESSO (
	IDPROCESSO INT NOT NULL
	, NOME VARCHAR(100) NOT NULL
	, DESCRICAO VARCHAR(100) NOT NULL
	, STATUS CHAR(1) NOT NULL
    , CONSTRAINT PK_PROCESSO PRIMARY KEY (IDPROCESSO)
);

CREATE TABLE EMPRESA (
    IDEMPRESA INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , IDPLANO_PADRAO INT 
    , DT_PRIMEIRO_CONTATO DATETIME NOT NULL
    , DT_INICIO_CONTRATO DATETIME NOT NULL
    , DT_FINAL_CONTRATO DATETIME NOT NULL
    , STATUS CHAR(1) NOT NULL
    , CONSTRAINT PK_EMPRESA PRIMARY KEY (IDEMPRESA)
    , CONSTRAINT FK_EMPRESA_PLANO FOREIGN KEY (IDPLANO_PADRAO) REFERENCES PLANO(IDPLANO)
);

CREATE TABLE EMPRESA_USUARIO (
    IDEMPRESA_USUARIO INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , IDUSUARIO INT NOT NULL
    , PAPEL VARCHAR(50) NOT NULL
    , DT_CADASTRO DATETIME NOT NULL
	, STATUS CHAR(1) NOT NULL
    , CONSTRAINT PK_EMPRESA_USUARIO PRIMARY KEY (IDEMPRESA_USUARIO)
    , CONSTRAINT FK_EMPRESA_USUARIO_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
    , CONSTRAINT FK_EMPRESA_USUARIO_USAURIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE CAMPANHA (
    IDCAMPANHA INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , IDUSUARIO_ANALISTA INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , OBJETIVO VARCHAR(300) NOT NULL
    , META VARCHAR(300) NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, STATUS CHAR(1) NOT NULL
	, STATUS_KAMBAM CHAR(1) NOT NULL
    , CONSTRAINT PK_CAMPANHA PRIMARY KEY (IDCAMPANHA)
    , CONSTRAINT FK_CAMPANHA_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
);

CREATE TABLE ARQUIVO (
	IDARQUIVO INT IDENTITY(1,1) NOT NULL
    , IDCAMPANHA INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, IDENTIFICACAO VARCHAR(300) NOT NULL
	, LOCALIZACAO_CONTAINER VARCHAR(300) NOT NULL
    , DT_IMPORTACAO DATETIME NOT NULL
    , CONSTRAINT PK_ARQUIVO PRIMARY KEY (IDARQUIVO)
    , CONSTRAINT FK_ARQUIVO_CAMPANHA FOREIGN KEY (IDCAMPANHA) REFERENCES CAMPANHA(IDCAMPANHA)
);

CREATE TABLE PROCESSO_CAMPANHA (
	IDPROCESSO_CAMPANHA INT IDENTITY(1,1) NOT NULL
    , IDCAMPANHA INT NOT NULL
    , IDPROCESSO INT NOT NULL
    , IDUSUARIO_RESPONSAVEL INT NOT NULL
    , OBSERVACAO VARCHAR(300) NOT NULL
    , DT_INICIO_EXECUCAO DATETIME NOT NULL
    , DT_FINAL_EXECUCAO DATETIME NOT NULL
    , CONSTRAINT PK_PROCESSO_CAMPANHA PRIMARY KEY (IDPROCESSO_CAMPANHA)
    , CONSTRAINT FK_PROCESSO_CAMPANHA_CAMPANHA FOREIGN KEY (IDCAMPANHA) REFERENCES CAMPANHA(IDCAMPANHA)
    , CONSTRAINT FK_PROCESSO_CAMPANHA_PROCESSO FOREIGN KEY (IDPROCESSO) REFERENCES PROCESSO(IDPROCESSO)
    , CONSTRAINT FK_PROCESSO_CAMPANHA_USUARIO FOREIGN KEY (IDUSUARIO_RESPONSAVEL) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE RELATORIO (
	IDRELATORIO INT IDENTITY(1,1) NOT NULL
    , IDCAMPANHA INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, IDENTIFICACAO VARCHAR(300) NOT NULL
	, LOCALIZACAO_CONTAINER VARCHAR(300) NOT NULL
    , DT_GERACAO DATETIME NOT NULL
    , CONSTRAINT PK_RELATORIO PRIMARY KEY (IDRELATORIO)
    , CONSTRAINT FK_RELATORIO_CAMPANHA FOREIGN KEY (IDCAMPANHA) REFERENCES CAMPANHA(IDCAMPANHA)
);

CREATE TABLE FATURA (
	IDFATURA INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DT_REFERENCIA DATE NOT NULL
	, VALOR DECIMAL(8,2) NOT NULL
	, DT_VENCIMENTO DATE NOT NULL
    , VALOR_PAGO DECIMAL(8,2) NOT NULL
    , DT_PAGAMENTO DATE NOT NULL
    , CONSTRAINT PK_FATURA PRIMARY KEY (IDFATURA)
    , CONSTRAINT FK_FATURA_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
);

CREATE TABLE ITEM_FATURA (
	IDITEM_FATURA INT IDENTITY(1,1) NOT NULL
	, IDFATURA INT NOT NULL
    , IDCAMPANHA INT NOT NULL
	, IDPLANO_ITEM INT NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, VALOR_UNITARIO DECIMAL(8,2) NOT NULL
	, CAMPANHA_PARCEIRO_GROWTH CHAR(1) NOT NULL
    , CONSTRAINT PK_ITEM_FATURA PRIMARY KEY (IDITEM_FATURA)
    , CONSTRAINT FK_ITEM_FATURA_FATURA FOREIGN KEY (IDFATURA) REFERENCES FATURA(IDFATURA)
    , CONSTRAINT FK_ITEM_FATURA_CAMPANHA FOREIGN KEY (IDCAMPANHA) REFERENCES CAMPANHA(IDCAMPANHA)
    , CONSTRAINT FK_ITEM_FATURA_PLANO FOREIGN KEY (IDPLANO_ITEM) REFERENCES PLANO(IDPLANO)
);


CREATE TRIGGER TR_CONTATO_INSERT ON CONTATO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO CONTATO (IDCONTATO, NOME, EMAIL, TELEFONE, MENSAGEM, TIPO, VISUALIZADO, RESPONDIDO, INTERESSE, CLIENTE, ATIVO, DT_CONTATO)
    SELECT 
		IDCONTATO
		, NOME
		, EMAIL
		, TELEFONE
		, MENSAGEM
		, TIPO
		, 'N' 				--VISUALIZADO
		, 'N' 				--RESPONDIDO
		, 'N' 				--INTERESSE
		, 'N' 				--CLIENTE
		, 'S' 				--ATIVO
		, GETDATE() 		--DT_CONTATO
    FROM inserted;
END;

CREATE TRIGGER TR_USUARIO_INSERT ON USUARIO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO USUARIO (NOME, EMAIL, SENHA, ATIVO, TIPO, DT_ATIVACAO, DESATIVADO, DT_DESATIVADO, DT_CADASTRO, DT_ATUALIZADO)
    SELECT 
		NOME
		, EMAIL
		, SENHA
    	, 'N'			-- ATIVO
        , 'NORMAL'      -- TIPO
        , NULL          -- DT_ATIVACAO
        , 'N'           -- DESATIVADO
        , NULL          -- DT_DESATIVADO
        , GETDATE()     -- DT_CADASTRO
        , GETDATE()     -- DT_ATUALIZADO
    FROM inserted;
END;

CREATE TRIGGER TR_USUARIO_UPDATE ON USUARIO AFTER UPDATE AS 
BEGIN 
	UPDATE U
    SET 
		DT_ATUALIZADO = GETDATE()
		, TIPO = CASE 
                 	WHEN D.IDUSUARIO = 1 THEN 'ADMINISTRADOR'
                   	ELSE U.TIPO
               	 END
    FROM USUARIO U
    INNER JOIN inserted I ON U.IDUSUARIO = I.IDUSUARIO
    INNER JOIN deleted D ON U.IDUSUARIO = D.IDUSUARIO
   	INNER JOIN updated U ON U.IDUSUARIO = D.IDUSUARIO;
END;

CREATE TRIGGER TR_TOKEN_BEFORE_INSERT ON TOKEN INSTEAD OF INSERT AS  
BEGIN 
	INSERT INTO TOKEN (IDUSUARIO, TOKEN, SECRET_KEY, DT_CRIACAO, DT_EXPIRACAO, DESATIVADO, DT_DESATIVADO, DT_ATUALIZADO)
	SELECT	
		IDUSUARIO
    	, TOKEN
    	, SECRET_KEY
    	, GETDATE()			-- DT_CRIACAO
    	, DT_EXPIRACAO
    	, 'N'				-- DESATIVADO
    	, NULL				-- DT_DESATIVADO
    	, GETDATE()			-- DT_ATUALIZADO
	FROM inserted; 
END;

CREATE TRIGGER TR_TOKEN_BEFORE_UPDATE ON TOKEN AFTER UPDATE AS 
BEGIN    
	UPDATE T
    SET 
	    IDUSUARIO = D.IDUSUARIO
	    , TOKEN = D.TOKEN
	    , SECRET_KEY = D.SECRET_KEY
	    , DT_CRIACAO = D.DT_CRIACAO
	    , DT_EXPIRACAO = D.DT_EXPIRACAO    
	    , DT_ATUALIZADO = GETDATE() 
    FROM TOKEN T
    INNER JOIN deleted D ON T.IDTOKEN = D.IDTOKEN;   
END;

CREATE TRIGGER TR_REGISTRO_BEFORE_INSERT ON REGISTRO INSTEAD OF INSERT AS
BEGIN 
	INSERT INTO REGISTRO (IDREGISTRO, IDUSUARIO, IDTOKEN, MODULO, ACAO, DT_REGISTRO)
	SELECT	
		IDREGISTRO
    	, IDUSUARIO
    	, IDTOKEN
    	, MODULO
    	, ACAO
    	, GETDATE()			-- DT_REGISTRO
	FROM inserted; 
END;

CREATE TRIGGER TR_HISTORICO_ACESSO_BEFORE_INSERT ON HISTORICO_ACESSO INSTEAD OF INSERT AS  
BEGIN 
	INSERT INTO HISTORICO_ACESSO (IDHISTORICO_ACESSO, IDUSUARIO, ROTA, DT_ACESSO)
	SELECT	
		IDHISTORICO_ACESSO
    	, IDUSUARIO
    	, ROTA
    	, GETDATE()			-- DT_DT_ACESSO
	FROM inserted; 
END;

CREATE VIEW VW_TOKEN AS (
SELECT 
    IDTOKEN
	, IDUSUARIO
    , TOKEN
    , SECRET_KEY
    , DT_CRIACAO
    , DT_EXPIRACAO
    , DESATIVADO
    , DT_DESATIVADO
    , CASE WHEN DT_EXPIRACAO > GETUTCDATE() AND ISNULL(DESATIVADO, 'N') = 'N' then 'S' ELSE 'N' END ATIVO
FROM
	TOKEN
);

CREATE VIEW VW_USUARIO AS (
SELECT 
    IDUSUARIO
    , NOME
    , EMAIL
    , ATIVO
    , DT_ATIVACAO
    , DESATIVADO
    , DT_DESATIVADO
    , DT_CADASTRO
    , DT_ATUALIZADO
    , (SELECT top 1 TOKEN FROM VW_TOKEN T WHERE T.IDUSUARIO = U.IDUSUARIO AND ATIVO = 'S' ORDER BY IDTOKEN DESC) AS TOKEN_ATIVO
    , TIPO
FROM
	USUARIO U
);



SELECT * FROM CONTATO;
SELECT * FROM USUARIO;
SELECT * FROM REGISTRO;
SELECT * FROM TOKEN;
SELECT * FROM HISTORICO_ACESSO;
SELECT * FROM ATALHO;

SELECT * FROM VW_TOKEN;
SELECT * FROM VW_USUARIO;
