DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS REGISTRO;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS USUARIO;

/* Criando a tabela de contatos do sites*/
CREATE TABLE CONTATO (
	IDCONTATO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL
    , TELEFONE VARCHAR(30) NOT NULL
    , MENSAGEM TEXT
    , TIPO VARCHAR(30) NOT NULL
    , VISUALIZADO CHAR(1) NULL	-- INDICA SE O CONTATO FOI VISUALIZADO
    , RESPONDIDO CHAR(1) NULL	-- INDICA QUE JÁ ENTRAMOS EM CONTATO COM O SOLICITANTE
    , INTERESSE CHAR(1) NULL	-- INDICA QUE O CLIENTE ESTÁ INTERESSADO
    , CLIENTE CHAR(1) NULL		-- INDICA QUE O CONTATO VIROU UM CLIENTE
    , ATIVO CHAR(1) NULL		-- INDICA QUE O CONTATO AINDA ESTÁ ATIVO EM CONTATO
    , DT_CONTATO DATETIME NULL
    , CONSTRAINT FK_CONTATO PRIMARY KEY (IDCONTATO)
);


DROP TRIGGER IF EXISTS TR_CONTATO_INSERT;
CREATE TRIGGER TR_CONTATO_INSERT ON CONTATO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO CONTATO (IDCONTATO, NOME, EMAIL, TELEFONE, MENSAGEM, TIPO, VISUALIZADO, RESPONDIDO, INTERESSE, CLIENTE, ATIVO, DT_CONTATO)
    SELECT 
		IDCONTATO
		, NOME
		, EMAIL
		, TELEFONE
		, MENSAGEM
		, TIPO
		, 'N' 				--VISUALIZADO
		, 'N' 				--RESPONDIDO
		, 'N' 				--INTERESSE
		, 'N' 				--CLIENTE
		, 'S' 				--ATIVO
		, GETDATE() 		--DT_CONTATO
    FROM inserted;
END;

/* Criando a tabela de usuarios*/
CREATE TABLE USUARIO (
	IDUSUARIO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL UNIQUE
    , SENHA VARCHAR(200) NOT NULL
    , ATIVO CHAR(1) NOT NULL
    , DT_ATIVACAO DATETIME
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_CADASTRO DATETIME NOT NULL
    , DT_ATUALIZADO DATETIME NOT NULL
    , TIPO VARCHAR(15) NOT NULL
    , CONSTRAINT FK_USUARIO PRIMARY KEY (IDUSUARIO)
);

DROP TRIGGER IF EXISTS TR_USUARIO_INSERT;
CREATE TRIGGER TR_USUARIO_INSERT ON USUARIO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO USUARIO (NOME, EMAIL, SENHA, ATIVO, TIPO, DT_ATIVACAO, DESATIVADO, DT_DESATIVADO, DT_CADASTRO, DT_ATUALIZADO)
    SELECT 
		NOME
		, EMAIL
		, SENHA
    	, 'N'			-- ATIVO
        , 'NORMAL'      -- TIPO
        , NULL          -- DT_ATIVACAO
        , 'N'           -- DESATIVADO
        , NULL          -- DT_DESATIVADO
        , GETDATE()     -- DT_CADASTRO
        , GETDATE()     -- DT_ATUALIZADO
    FROM inserted;
END;

DROP TRIGGER IF EXISTS TR_USUARIO_UPDATE;
CREATE TRIGGER TR_USUARIO_UPDATE ON USUARIO AFTER UPDATE AS 
BEGIN 
	UPDATE U
    SET 
		DT_ATUALIZADO = GETDATE()
		, TIPO = CASE 
                 	WHEN D.IDUSUARIO = 1 THEN 'ADMINISTRADOR'
                   	ELSE U.TIPO
               	 END
    FROM USUARIO U
    INNER JOIN inserted I ON U.IDUSUARIO = I.IDUSUARIO
    INNER JOIN deleted D ON U.IDUSUARIO = D.IDUSUARIO
   	INNER JOIN updated U ON U.IDUSUARIO = D.IDUSUARIO;
END;


/* Criando a tabela de usuarios*/
CREATE TABLE TOKEN (
    IDTOKEN INT IDENTITY(1,1) NOT NULL
	, IDUSUARIO INT NOT NULL
    , TOKEN VARCHAR(200) NOT NULL
    , SECRET_KEY VARCHAR(200) NOT NULL
    , DT_CRIACAO DATETIME NOT NULL
    , DT_EXPIRACAO DATETIME NOT NULL
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_ATUALIZADO DATETIME NOT NULL
    , CONSTRAINT FK_TOKEN PRIMARY KEY (IDTOKEN)
    , CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_INSERT;
CREATE TRIGGER TR_TOKEN_BEFORE_INSERT ON TOKEN INSTEAD OF INSERT AS  
BEGIN 
	INSERT INTO TOKEN (IDUSUARIO, TOKEN, SECRET_KEY, DT_CRIACAO, DT_EXPIRACAO, DESATIVADO, DT_DESATIVADO, DT_ATUALIZADO)
	SELECT	
		IDUSUARIO
    	, TOKEN
    	, SECRET_KEY
    	, GETDATE()			-- DT_CRIACAO
    	, DT_EXPIRACAO
    	, 'N'				-- DESATIVADO
    	, NULL				-- DT_DESATIVADO
    	, GETDATE()			-- DT_ATUALIZADO
	FROM inserted; 
END;

DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_UPDATE;
CREATE TRIGGER TR_TOKEN_BEFORE_UPDATE ON TOKEN AFTER UPDATE AS 
BEGIN    
	UPDATE T
    SET 
	    IDUSUARIO = D.IDUSUARIO
	    , TOKEN = D.TOKEN
	    , SECRET_KEY = D.SECRET_KEY
	    , DT_CRIACAO = D.DT_CRIACAO
	    , DT_EXPIRACAO = D.DT_EXPIRACAO    
	    , DT_ATUALIZADO = GETDATE() 
    FROM TOKEN T
    INNER JOIN deleted D ON T.IDTOKEN = D.IDTOKEN;   
END;

CREATE TABLE REGISTRO (
    IDREGISTRO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT NOT NULL
    , IDTOKEN INT
    , MODULO VARCHAR(200) NOT NULL
    , ACAO VARCHAR(200) NOT NULL
    , DT_REGISTRO DATETIME NOT NULL
    , CONSTRAINT FK_REGISTRO PRIMARY KEY (IDREGISTRO)
    , CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_REGISTRO_TOKEN FOREIGN KEY (IDTOKEN) REFERENCES TOKEN(IDTOKEN)
);

DROP TRIGGER IF EXISTS TR_REGISTRO_BEFORE_INSERT;
CREATE TRIGGER TR_REGISTRO_BEFORE_INSERT ON REGISTRO INSTEAD OF INSERT AS
BEGIN 
	INSERT INTO REGISTRO (IDREGISTRO, IDUSUARIO, IDTOKEN, MODULO, ACAO, DT_REGISTRO)
	SELECT	
		IDREGISTRO
    	, IDUSUARIO
    	, IDTOKEN
    	, MODULO
    	, ACAO
    	, GETDATE()			-- DT_REGISTRO
	FROM inserted; 
END;

DROP VIEW IF EXISTS VW_TOKEN;
CREATE VIEW VW_TOKEN AS (
SELECT 
    IDTOKEN
	, IDUSUARIO
    , TOKEN
    , SECRET_KEY
    , DT_CRIACAO
    , DT_EXPIRACAO
    , DESATIVADO
    , DT_DESATIVADO
    , CASE WHEN DT_EXPIRACAO > GETUTCDATE() AND ISNULL(DESATIVADO, 'N') = 'N' then 'S' ELSE 'N' END ATIVO
FROM
	TOKEN
);

DROP VIEW IF EXISTS VW_USUARIO;
CREATE VIEW VW_USUARIO AS (
SELECT 
    IDUSUARIO
    , NOME
    , EMAIL
    , ATIVO
    , DT_ATIVACAO
    , DESATIVADO
    , DT_DESATIVADO
    , DT_CADASTRO
    , DT_ATUALIZADO
    , (SELECT top 1 TOKEN FROM VW_TOKEN T WHERE T.IDUSUARIO = U.IDUSUARIO AND ATIVO = 'S' ORDER BY IDTOKEN DESC) AS TOKEN_ATIVO
    , TIPO
FROM
	USUARIO U
);

INSERT INTO USUARIO(NOME, EMAIL, SENHA)VALUES('ADMIN', 'ADMIN@EMAIL.COM', 'ADMIN');

SELECT * FROM VW_USUARIO;

SELECT * FROM CONTATO;