DROP VIEW IF EXISTS VW_TOKEN;
DROP VIEW IF EXISTS VW_USUARIO;

DROP TRIGGER IF EXISTS TR_CONTATO_INSERT;
DROP TRIGGER IF EXISTS TR_HISTORICO_ACESSO_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_REGISTRO_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_UPDATE;
DROP TRIGGER IF EXISTS TR_TOKEN_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TR_USUARIO_UPDATE;
DROP TRIGGER IF EXISTS TR_USUARIO_INSERT;

DROP TABLE IF EXISTS ATIVIDADE;
DROP TABLE IF EXISTS HISTORICO_ACESSO;
DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS ATALHO;
DROP TABLE IF EXISTS REGISTRO;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS ARQUIVO;
DROP TABLE IF EXISTS PROCESSO_ESTUDO;
DROP TABLE IF EXISTS PROCESSO_ITEM_ACAO;
DROP TABLE IF EXISTS ACAO;
DROP TABLE IF EXISTS PROCESSO_ITEM;
DROP TABLE IF EXISTS PROCESSO;
DROP TABLE IF EXISTS RELATORIO;
DROP TABLE IF EXISTS ITEM_FATURA;
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS FATURA;
DROP TABLE IF EXISTS ESTUDO;
DROP TABLE IF EXISTS EMPRESA_USUARIO;
DROP TABLE IF EXISTS PLANO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS USUARIO;


/* Criando a tabela de contatos do sites*/
CREATE TABLE CONTATO (
	IDCONTATO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL
    , TELEFONE VARCHAR(30) NOT NULL  
    , MENSAGEM TEXT                 -- MENSAGEM ENVIADA JUNTO COM A SOLICITA��O DE CONTATO
    , TIPO VARCHAR(300) NOT NULL    -- 1-Quero uma análise diagnóstica gratuita, 2-Analisar minha campanha, 3-Quero ser parceiro growth, 4-Quero uma apresentação agendada
    , VISUALIZADO CHAR(1) NULL	    -- INDICA SE O CONTATO FOI VISUALIZADO
    , RESPONDIDO CHAR(1) NULL	    -- INDICA QUE SE ENTRAMOS EM CONTATO COM O SOLICITANTE
    , INTERESSE CHAR(1) NULL	    -- INDICA QUE O CLIENTE ESTA INTERESSADO
    , CLIENTE CHAR(1) NULL		    -- INDICA QUE O CONTATO VIROU UM CLIENTE
    , ATIVO CHAR(1) NULL		    -- INDICA QUE O CONTATO AINDA ESTA ATIVO EM CONTATO
    , DT_CONTATO DATETIME NULL      -- DATA DA REALIZA��O DO CONTATO
    , CONSTRAINT PK_CONTATO PRIMARY KEY (IDCONTATO)
);

/* Criando a tabela de usuarios*/
CREATE TABLE USUARIO (
	IDUSUARIO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL UNIQUE
    , SENHA VARCHAR(200) NOT NULL
    , ATIVO CHAR(1) NOT NULL            -- S: INDICA ATIVO, N: INDICA QUE O USUARIO N�O ATIVOU O ACESSO
    , DT_ATIVACAO DATETIME              -- DATA DE ATIVA��O DO USUARIO
    , DESATIVADO CHAR(1) NOT NULL       -- S: INDICA QUE O USUARIO FOI DESATIVADO, N: INDICA QUE O USUARIO AINDA EST� ATIVO
    , DT_DESATIVADO DATETIME            -- DATA DE DESATIVA��O
    , DT_CADASTRO DATETIME NOT NULL     -- DATA DE CADASTRO
    , DT_ATUALIZADO DATETIME NOT NULL   -- DATA DA ULTIMA ATULIZA��O
    , TIPO VARCHAR(15) NOT NULL         -- TIPO DE USUARIO, ADMIN, CLIENTE, ANALISTA, CIENTISTA
    , CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO)
);

/* Criando a tabela de usuarios*/
CREATE TABLE TOKEN (
    IDTOKEN INT IDENTITY(1,1) NOT NULL
	, IDUSUARIO INT NOT NULL            -- USUARIO QUE GEROU O TOKEN (TOKEN FICA ASSOCIADO AO USUARIO)
    , TOKEN VARCHAR(200) NOT NULL       -- TOKEM DE ACESSO VIA API
    , SECRET_KEY VARCHAR(200) NOT NULL  -- SENHA USADA PARA GERAR O TOKEN
    , DT_CRIACAO DATETIME NOT NULL      -- DATA DA CRIA��O DO TOKEN
    , DT_EXPIRACAO DATETIME NOT NULL    -- DATA DE VALIDADE DO TOKEN
    , DESATIVADO CHAR(1) NOT NULL       -- S: INDICA QUE O USUARIO FOI DESATIVADO, N: INDICA QUE O USUARIO AINDA EST� ATIVO, INDICA SE O TOKEN FOI DESATIVADO, QUANDO GERADO UM NOVO TOKEN O ANTIGO � DESATIVADO
    , DT_DESATIVADO DATETIME            -- DATA QUE FOI DESATIVADO
    , DT_ATUALIZADO DATETIME NOT NULL   -- DATA DE ATUALIZA��O
    , CONSTRAINT PK_TOKEN PRIMARY KEY (IDTOKEN)
    , CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE REGISTRO (
    IDREGISTRO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT NOT NULL            -- REGISTRO DE ACESSO VIA TOKEM
    , IDTOKEN INT                       -- TOKEN UTILIZADO
    , MODULO VARCHAR(200) NOT NULL      -- MODULO ACESSADO
    , ACAO VARCHAR(200) NOT NULL        -- ACAO REALIZADA
    , DT_REGISTRO DATETIME NOT NULL     -- DATA DO REGISTRO DE ACESSO
    , CONSTRAINT PK_REGISTRO PRIMARY KEY (IDREGISTRO)
    , CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_REGISTRO_TOKEN FOREIGN KEY (IDTOKEN) REFERENCES TOKEN(IDTOKEN)
);

CREATE TABLE HISTORICO_ACESSO (
    IDHISTORICO_ACESSO INT IDENTITY(1,1) NOT NULL 
	, IDUSUARIO INT                 -- HISTORICO DE ACESSO NA APLICA��O
    , ROTA TEXT                     -- ROTA ACESSADA
    , METODO VARCHAR(10)            -- ROTA ACESSADA
    , IP TEXT                       -- DADOS DE JSON RECEBIDO
    , PATH_SERVER TEXT              -- DADOS DE JSON RECEBIDO
    , FULL_URL TEXT                 -- DADOS DE JSON RECEBIDO
    , QUERY_STRING TEXT             -- DADOS DE JSON RECEBIDO
    , FORM_DATA TEXT                -- DADOS DE JSON RECEBIDO
    , JSON_DATA TEXT                -- DADOS DE JSON RECEBIDO
    , DT_ACESSO DATETIME NOT NULL   -- DATA DO ACESSO
    , CONSTRAINT PK_HISTORICO_ACESSO PRIMARY KEY (IDHISTORICO_ACESSO)
    , CONSTRAINT FK_HISTORICO_ACESSO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE ATALHO (
    IDATALHO INT IDENTITY(1,1) NOT NULL     -- IDENTIFICA��O DO ATALHO DO USUARIO
	, IDUSUARIO INT NOT NULL                -- USUARIO QUE PERTENCE O ATALHO
    , GRUPO VARCHAR(100) NOT NULL           -- GRUPO ONDE VAI APARECE O ATALHO
    , NOME VARCHAR(100) NOT NULL            -- NOME DO ATALHO
    , ROTA VARCHAR(250) NOT NULL            -- ROTA QUE O ATALHO ACESSA (DEVE SER APENAS PARA TELA DE DETALHE DO MODULO OU TELA GERENCIAL)
    , CONSTRAINT PK_ATALHO PRIMARY KEY (IDATALHO)
    , CONSTRAINT FK_ATALHO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE PLANO (
    IDPLANO INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(100) NOT NULL            -- NOME DO PLANO DE PAGAMENTO
    , DESCRICAO VARCHAR(300) NOT NULL       -- DESCRI��O DO PLANO DE PAGAMENTO
    , PARCEIRO_GROWTH CHAR(1) NOT NULL      -- INDICA SE O PLANO � REFERENTE A UM PARCEIRO (CONTRATO MENSAL E OU COBRAN�A INDIVIDUAL MAS COM DESCONTO)
    , VALOR DECIMAL(8,2)                    -- VALOR DO PLANO
    , STATUS CHAR(1) NOT NULL               -- A: INDICA QUE O PLANO � ATIVO, D: INDICA QUE O PLANO EST� DESATIVADO
	, DT_INICIAL_VIGENCIA DATETIME          -- DATA INICIAL QUE O PLANO EST� EM VIGENCIA
	, DT_FINAL_VIGENCIA DATETIME            -- DATA FINAL QUE O PLANO EST� EM VIGENCIA
    , CONSTRAINT PK_PLANO PRIMARY KEY (IDPLANO)
);

CREATE TABLE PROCESSO (
	IDPROCESSO INT IDENTITY(1,1) NOT NULL       -- IDENTIFICADOR DE PROCESSO QUE PODEM SER EXECUTADO NO ESTUDO
	, NOME VARCHAR(100) NOT NULL                -- NOME DO PROCESSO
	, DESCRICAO VARCHAR(100) NOT NULL           -- DESCRI��O DO PROCESO
	, STATUS CHAR(1) NOT NULL                   -- A: INDICA QUE O PROCESSO PODE SER USADO, D: INDICA QUE O PROCESSO EST� DESATIVADO
    , CONSTRAINT PK_PROCESSO PRIMARY KEY (IDPROCESSO)
);

CREATE TABLE PROCESSO_ITEM (
    IDPROCESSO_ITEM INT IDENTITY(1,1) NOT NULL       
	, IDPROCESSO INT NOT NULL
	, NOME VARCHAR(100) NOT NULL
	, DESCRICAO VARCHAR(100) NOT NULL
	, STATUS CHAR(1) NOT NULL
    , ORDEM INT NOT NULL
    , CONSTRAINT PK_PROCESSO_ITEM PRIMARY KEY (IDPROCESSO_ITEM)
    , CONSTRAINT PK_PROCESSO_ITEM_PROCESSO FOREIGN KEY (IDPROCESSO) REFERENCES PROCESSO(IDPROCESSO)
);

CREATE TABLE ACAO (
    IDACAO INT IDENTITY(1,1) NOT NULL       
	, NOME VARCHAR(100) NOT NULL
	, DESCRICAO VARCHAR(100) NOT NULL
	, STATUS CHAR(1) NOT NULL
    , CONSTRAINT PK_ACAO PRIMARY KEY (IDACAO)
);

CREATE TABLE PROCESSO_ITEM_ACAO (
    IDPROCESSO_ITEM INT NOT NULL       
    , IDACAO INT NOT NULL       
	, VALOR TEXT NOT NULL
	, STATUS CHAR(1) NOT NULL
    , CONSTRAINT PK_PROCESSO_ITEM_ACAO PRIMARY KEY (IDPROCESSO_ITEM, IDACAO)
    , CONSTRAINT PK_PROCESSO_ITEM_ACAO_PROCESSO_ITEM FOREIGN KEY (IDPROCESSO_ITEM) REFERENCES PROCESSO_ITEM(IDPROCESSO_ITEM)
    , CONSTRAINT PK_PROCESSO_ITEM_ACAO_ACAO FOREIGN KEY (IDACAO) REFERENCES ACAO(IDACAO)
);

CREATE TABLE EMPRESA (
    IDEMPRESA INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(200) NOT NULL                -- NOME DA EMPRESA
    , IDPLANO_PADRAO INT                        -- PLANO PADR�O USADO PELA EMPRESA
    , DT_PRIMEIRO_CONTATO DATETIME NOT NULL     -- DATA DO PRIMERIO CONTATO
    , DT_INICIO_CONTRATO DATETIME NOT NULL      -- INICIO DO CONTRATO VIGENTE
    , DT_FINAL_CONTRATO DATETIME NOT NULL       -- TERMINO DO CONTRATO VIGENTE
    , STATUS CHAR(1) NOT NULL                   -- A: EMPRESA ATIVA, P: PARCEIRO ATIVO, D:DESATIVADA 
    , CONSTRAINT PK_EMPRESA PRIMARY KEY (IDEMPRESA)
    , CONSTRAINT FK_EMPRESA_PLANO FOREIGN KEY (IDPLANO_PADRAO) REFERENCES PLANO(IDPLANO)
);

CREATE TABLE CONTRATO (
    IDCONTRATO INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , IDUSUARIO_RESPONSAVEL INT NOT NULL
    , IDUSUARIO_VENDEDOR_RESPONSAVEL INT NOT NULL
    , DESCRICAO VARCHAR(300) NOT NULL                   -- DESCRI��O DO PLANO DE PAGAMENTO
    , STATUS CHAR(1) NOT NULL                           -- P: INDICA QUE O CONTRATO EST� PENDENTE, S: CONTRATO ASSINADO, V: CONTRATO EM VIGENCIA, T: TERMINO DO CONTRATO, R: RESSINDIDO, C: PROCESSO DE CONTRATO CANCELADO
	, DT_CADATRO DATETIME                               -- DATA DE INICIAL DE CADASTRO DO CONTRATO
	, DT_ASSINATURA DATETIME                            -- DATA DA ASSINATURA DO CONTRATO
	, DT_ATUALIZACAO DATETIME                           -- DATA DA ULTIMA ATUALIZA��O DO CONTRATO
	, DT_INICIAL_VIGENCIA DATETIME                      -- DATA DO INICIO DA VIGENCIA
	, DT_FINAL_VIGENCIA DATETIME                        -- DATA DO TERMINO DA VIGENCIA
    , CONSTRAINT PK_CONTRATO PRIMARY KEY (IDCONTRATO)
    , CONSTRAINT FK_CONTRATO_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
    , CONSTRAINT FK_CONTRATO_USUARIO_RESPONSAVEL FOREIGN KEY (IDUSUARIO_RESPONSAVEL) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_CONTRATO_USUARIO_VENDEDOR FOREIGN KEY (IDUSUARIO_VENDEDOR_RESPONSAVEL) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE EMPRESA_USUARIO (
    IDEMPRESA_USUARIO INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL                    -- EMPRESA
    , IDUSUARIO INT NOT NULL                    -- USUARIO ASSOCIADO 
    , PAPEL VARCHAR(50) NOT NULL                -- PAPEL O USUARIO NA EMPRESA (Cliente responsavel, analista responsavel, cientista responsavel, vendedor responsaval)
    , DT_CADASTRO DATETIME NOT NULL             -- DATA DE CADASTRO DO CONTATO
	, STATUS CHAR(1) NOT NULL                   -- SITUA��O DO RELACIONAMENTO A: ATIVO, D: DESATIVADO
    , CONSTRAINT PK_EMPRESA_USUARIO PRIMARY KEY (IDEMPRESA_USUARIO)
    , CONSTRAINT FK_EMPRESA_USUARIO_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
    , CONSTRAINT FK_EMPRESA_USUARIO_USAURIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE ESTUDO (
    IDESTUDO INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , IDUSUARIO_ANALISTA INT NOT NULL
    , TIPO VARCHAR(150) NOT NULL            -- TIPO DE ESTUDO, CAMPANHA DE MARKETING, ANALISE DE DESEMPENHO....
    , NOME VARCHAR(300) NOT NULL
    , OBJETIVO VARCHAR(300) NOT NULL
    , META VARCHAR(300) NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, STATUS CHAR(1) NOT NULL               -- A: ATIVO, D: DESATIVADO
	, STATUS_KAMBAM CHAR(1) NOT NULL
    , CONSTRAINT PK_ESTUDO PRIMARY KEY (IDESTUDO)
    , CONSTRAINT FK_ESTUDO_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
);

CREATE TABLE ARQUIVO (
	IDARQUIVO INT IDENTITY(1,1) NOT NULL
    , IDESTUDO INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DECRICAO VARCHAR(300) NOT NULL
	, IDENTIFICACAO VARCHAR(300) NOT NULL
	, LOCALIZACAO_CONTAINER VARCHAR(300) NOT NULL
    , DT_IMPORTACAO DATETIME NOT NULL
    , CONSTRAINT PK_ARQUIVO PRIMARY KEY (IDARQUIVO)
    , CONSTRAINT FK_ARQUIVO_ESTUDO FOREIGN KEY (IDESTUDO) REFERENCES ESTUDO(IDESTUDO)
);

CREATE TABLE PROCESSO_ESTUDO (
	IDPROCESSO_ESTUDO INT IDENTITY(1,1) NOT NULL
    , IDESTUDO INT NOT NULL
    , IDPROCESSO INT NOT NULL
    , IDUSUARIO_RESPONSAVEL INT NOT NULL
    , OBSERVACAO VARCHAR(300) NOT NULL
    , DT_INICIO_EXECUCAO DATETIME NOT NULL
    , DT_FINAL_EXECUCAO DATETIME NOT NULL
    , CONSTRAINT PK_PROCESSO_ESTUDO PRIMARY KEY (IDPROCESSO_ESTUDO)
    , CONSTRAINT FK_PROCESSO_ESTUDO_ESTUDO FOREIGN KEY (IDESTUDO) REFERENCES ESTUDO(IDESTUDO)
    , CONSTRAINT FK_PROCESSO_ESTUDO_PROCESSO FOREIGN KEY (IDPROCESSO) REFERENCES PROCESSO(IDPROCESSO)
    , CONSTRAINT FK_PROCESSO_ESTUDO_USUARIO FOREIGN KEY (IDUSUARIO_RESPONSAVEL) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE RELATORIO (
	IDRELATORIO INT IDENTITY(1,1) NOT NULL
    , IDESTUDO INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DESCRICAO VARCHAR(300) NOT NULL
	, IDENTIFICACAO VARCHAR(300) NOT NULL
	, LOCALIZACAO_CONTAINER VARCHAR(300) NOT NULL
    , DT_GERACAO DATETIME NOT NULL
    , CONSTRAINT PK_RELATORIO PRIMARY KEY (IDRELATORIO)
    , CONSTRAINT FK_RELATORIO_ESTUDO FOREIGN KEY (IDESTUDO) REFERENCES ESTUDO(IDESTUDO)
);

CREATE TABLE FATURA (
	IDFATURA INT IDENTITY(1,1) NOT NULL
    , IDEMPRESA INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DT_REFERENCIA DATE NOT NULL
	, VALOR DECIMAL(8,2) NOT NULL
	, DT_VENCIMENTO DATE NOT NULL
    , VALOR_PAGO DECIMAL(8,2) NOT NULL
    , DT_PAGAMENTO DATE NOT NULL
    , CONSTRAINT PK_FATURA PRIMARY KEY (IDFATURA)
    , CONSTRAINT FK_FATURA_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
);

CREATE TABLE ITEM_FATURA (
	IDITEM_FATURA INT IDENTITY(1,1) NOT NULL
	, IDFATURA INT NOT NULL
    , IDESTUDO INT NOT NULL
	, IDPLANO_ITEM INT NOT NULL
    , DESCRICAO VARCHAR(300) NOT NULL
	, VALOR_UNITARIO DECIMAL(8,2) NOT NULL
	, ESTUDO_PARCEIRO_GROWTH CHAR(1) NOT NULL
    , CONSTRAINT PK_ITEM_FATURA PRIMARY KEY (IDITEM_FATURA)
    , CONSTRAINT FK_ITEM_FATURA_FATURA FOREIGN KEY (IDFATURA) REFERENCES FATURA(IDFATURA)
    , CONSTRAINT FK_ITEM_FATURA_ESTUDO FOREIGN KEY (IDESTUDO) REFERENCES ESTUDO(IDESTUDO)
    , CONSTRAINT FK_ITEM_FATURA_PLANO FOREIGN KEY (IDPLANO_ITEM) REFERENCES PLANO(IDPLANO)
);


CREATE TABLE ATIVIDADE (
	IDATIVIDADE INT IDENTITY(1,1) NOT NULL
	, IDUSUARIO INT NOT NULL
    , IDEMPRESA INT NOT NULL
	, IDESTUDO INT NOT NULL
    , NOME VARCHAR(300) NOT NULL
    , DESCRICAO TEXT
	, OBSERVACAO TEXT
	, PRIORIDADE INT NOT NULL
	, dh_inicio DATE NOT NULL
	, dh_termino DATE NOT NULL
	, STATUS CHAR(1) NOT NULL 
    , CONSTRAINT PK_ATIVIDADE PRIMARY KEY (IDATIVIDADE)
    , CONSTRAINT FK_ATIVIDADE_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_ATIVIDADE_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA)
    , CONSTRAINT FK_ATIVIDADE_ESTUDO FOREIGN KEY (IDESTUDO) REFERENCES ESTUDO(IDESTUDO)
);

GO

CREATE TRIGGER TR_CONTATO_INSERT ON CONTATO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO CONTATO (NOME, EMAIL, TELEFONE, MENSAGEM, TIPO, VISUALIZADO, RESPONDIDO, INTERESSE, CLIENTE, ATIVO, DT_CONTATO)
    SELECT 
		NOME
		, EMAIL
		, TELEFONE
		, MENSAGEM
		, TIPO
		, 'N' 				--VISUALIZADO
		, 'N' 				--RESPONDIDO
		, 'N' 				--INTERESSE
		, 'N' 				--CLIENTE
		, 'S' 				--ATIVO
		, GETDATE() 		--DT_CONTATO
    FROM inserted;
END;

GO

CREATE TRIGGER TR_USUARIO_INSERT ON USUARIO INSTEAD OF INSERT AS 
BEGIN 
	INSERT INTO USUARIO (NOME, EMAIL, SENHA, ATIVO, TIPO, DT_ATIVACAO, DESATIVADO, DT_DESATIVADO, DT_CADASTRO, DT_ATUALIZADO)
    SELECT 
		NOME
		, EMAIL
		, SENHA
    	, 'N'			-- ATIVO
        , 'NORMAL'      -- TIPO
        , NULL          -- DT_ATIVACAO
        , 'N'           -- DESATIVADO
        , NULL          -- DT_DESATIVADO
        , GETDATE()     -- DT_CADASTRO
        , GETDATE()     -- DT_ATUALIZADO
    FROM inserted;
END;

GO

CREATE TRIGGER TR_USUARIO_UPDATE ON USUARIO AFTER UPDATE AS 
BEGIN 
	UPDATE U
    SET 
		DT_ATUALIZADO = GETDATE()
		, TIPO = CASE 
                 	WHEN D.IDUSUARIO = 1 THEN 'ADMIN'
                   	ELSE U.TIPO
               	 END
    FROM USUARIO U
    INNER JOIN inserted I ON U.IDUSUARIO = I.IDUSUARIO
    INNER JOIN deleted D ON U.IDUSUARIO = D.IDUSUARIO
   	INNER JOIN updated U ON U.IDUSUARIO = D.IDUSUARIO;
END;

GO

CREATE TRIGGER TR_TOKEN_BEFORE_INSERT ON TOKEN INSTEAD OF INSERT AS  
BEGIN 
	INSERT INTO TOKEN (IDUSUARIO, TOKEN, SECRET_KEY, DT_CRIACAO, DT_EXPIRACAO, DESATIVADO, DT_DESATIVADO, DT_ATUALIZADO)
	SELECT	
		IDUSUARIO
    	, TOKEN
    	, SECRET_KEY
    	, GETDATE()			-- DT_CRIACAO
    	, DT_EXPIRACAO
    	, 'N'				-- DESATIVADO
    	, NULL				-- DT_DESATIVADO
    	, GETDATE()			-- DT_ATUALIZADO
	FROM inserted; 
END;

GO

CREATE TRIGGER TR_TOKEN_BEFORE_UPDATE ON TOKEN AFTER UPDATE AS 
BEGIN    
	UPDATE T
    SET 
	    IDUSUARIO = D.IDUSUARIO
	    , TOKEN = D.TOKEN
	    , SECRET_KEY = D.SECRET_KEY
	    , DT_CRIACAO = D.DT_CRIACAO
	    , DT_EXPIRACAO = D.DT_EXPIRACAO    
	    , DT_ATUALIZADO = GETDATE() 
    FROM TOKEN T
    INNER JOIN deleted D ON T.IDTOKEN = D.IDTOKEN;   
END;

GO

CREATE TRIGGER TR_REGISTRO_BEFORE_INSERT ON REGISTRO INSTEAD OF INSERT AS
BEGIN 
	INSERT INTO REGISTRO (IDUSUARIO, IDTOKEN, MODULO, ACAO, DT_REGISTRO)
	SELECT	
		IDUSUARIO
    	, IDTOKEN
    	, MODULO
    	, ACAO
    	, GETDATE()			-- DT_REGISTRO
	FROM inserted; 
END;

GO

CREATE TRIGGER TR_HISTORICO_ACESSO_BEFORE_INSERT ON HISTORICO_ACESSO INSTEAD OF INSERT AS  
BEGIN 
	INSERT INTO HISTORICO_ACESSO (IDUSUARIO, ROTA, METODO, IP, PATH_SERVER, FULL_URL, QUERY_STRING, FORM_DATA, JSON_DATA, DT_ACESSO)
	SELECT	
		IDUSUARIO
    	, ROTA
        , METODO
        , IP
        , PATH_SERVER
        , FULL_URL
        , QUERY_STRING
        , FORM_DATA
        , JSON_DATA
    	, GETDATE()			-- DT_DT_ACESSO
	FROM inserted; 
END;

GO

CREATE VIEW VW_TOKEN AS (
SELECT 
    IDTOKEN
	, IDUSUARIO
    , TOKEN
    , SECRET_KEY
    , DT_CRIACAO
    , DT_EXPIRACAO
    , DESATIVADO
    , DT_DESATIVADO
    , CASE WHEN DT_EXPIRACAO > GETUTCDATE() AND ISNULL(DESATIVADO, 'N') = 'N' then 'S' ELSE 'N' END ATIVO
FROM
	TOKEN
);

GO

CREATE VIEW VW_USUARIO AS (
SELECT 
    IDUSUARIO
    , NOME
    , EMAIL
    , ATIVO
    , DT_ATIVACAO
    , DESATIVADO
    , DT_DESATIVADO
    , DT_CADASTRO
    , DT_ATUALIZADO
    , (SELECT top 1 TOKEN FROM VW_TOKEN T WHERE T.IDUSUARIO = U.IDUSUARIO AND ATIVO = 'S' ORDER BY IDTOKEN DESC) AS TOKEN_ATIVO
    , TIPO
FROM
	USUARIO U
);

GO

/*
SELECT * FROM CONTATO;
SELECT * FROM USUARIO;
SELECT * FROM REGISTRO;
SELECT * FROM TOKEN;
SELECT * FROM HISTORICO_ACESSO;
SELECT * FROM ATALHO;

SELECT * FROM VW_TOKEN;
SELECT * FROM VW_USUARIO;

*/

