DROP DATABASE IF EXISTS DBFEATURESTORE;
CREATE DATABASE DBFEATURESTORE;
USE DBFEATURESTORE;

CREATE TABLE IF NOT EXISTS USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(200) NOT NULL
    , EMAIL VARCHAR(200) NOT NULL UNIQUE
    , SENHA VARCHAR(200) NOT NULL
    , ATIVO CHAR(1) NOT NULL
    , DT_ATIVACAO DATETIME
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_CADASTRO DATETIME NOT NULL
    , DT_ATUALIZADO DATETIME NOT NULL
    , CONSTRAINT FK_USUARIO PRIMARY KEY (IDUSUARIO)
);

DELIMITER $$
CREATE TRIGGER TR_USUARIO_BEFORE_INSERT BEFORE INSERT ON USUARIO FOR EACH ROW 
BEGIN 
    SET NEW.ATIVO = 'N';
    SET NEW.DT_ATIVACAO = NULL;
    SET NEW.DESATIVADO = 'N';
    SET NEW.DT_DESATIVADO = NULL;
    SET NEW.DT_CADASTRO = NOW();
    SET NEW.DT_ATUALIZADO = NOW();
END $$

CREATE TRIGGER TR_USUARIO_BEFORE_UPDATE BEFORE UPDATE ON USUARIO FOR EACH ROW 
BEGIN 
    SET NEW.DT_ATUALIZADO = NOW();
END $$
DELIMITER ;

CREATE TABLE IF NOT EXISTS TOKEN (
    IDTOKEN INT NOT NULL AUTO_INCREMENT
	, IDUSUARIO INT NOT NULL
    , TOKEN VARCHAR(200) NOT NULL
    , SECRET_KEY VARCHAR(200) NOT NULL
    , DT_CRIACAO DATETIME NOT NULL
    , DT_EXPIRACAO DATETIME NOT NULL
    , DESATIVADO CHAR(1) NOT NULL
    , DT_DESATIVADO DATETIME
    , DT_ATUALIZADO DATETIME NOT NULL
    , CONSTRAINT FK_TOKEN PRIMARY KEY (IDTOKEN)
    , CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

DELIMITER $$
CREATE PROCEDURE SP_INCLUIR_TOKEN(pIDUSUARIO INT, pTOKEN VARCHAR(200), pSECRET_KEY VARCHAR(200), pDT_EXPIRACAO DATETIME)
BEGIN
	-- DESATIVANDO OS TOKENS EXISTENTE
	UPDATE TOKEN
    SET DESATIVADO = 'N', DT_DESATIVADO = NULL
	WHERE IDUSUARIO = pIDUSUARIO;
    
	-- INCLUINDO NOVO TOKEN
	INSERT INTO TOKEN(IDUSUARIO, TOKEN, SECRET_KEY, DT_EXPIRACAO)
    VALUES(pIDUSUARIO, pTOKEN, pSECRET_KEY, pDT_EXPIRACAO );
END $$

CREATE TRIGGER TR_TOKEN_BEFORE_INSERT BEFORE INSERT ON TOKEN FOR EACH ROW 
BEGIN 
    SET NEW.DT_CRIACAO = NOW();
    SET NEW.DESATIVADO = 'N';
    SET NEW.DT_DESATIVADO = NULL;
    SET NEW.DT_ATUALIZADO = NOW(); 
END $$

CREATE TRIGGER TR_TOKEN_BEFORE_UPDATE BEFORE UPDATE ON TOKEN FOR EACH ROW 
BEGIN 
    SET NEW.IDUSUARIO = OLD.IDUSUARIO;
    SET NEW.TOKEN = OLD.TOKEN;
    SET NEW.SECRET_KEY = OLD.SECRET_KEY;
    SET NEW.DT_CRIACAO = OLD.DT_CRIACAO;
    SET NEW.DT_EXPIRACAO = OLD.DT_EXPIRACAO;
    
    SET NEW.DT_ATUALIZADO = NOW(); 
END $$
DELIMITER ;

CREATE TABLE IF NOT EXISTS REGISTRO (
    IDREGISTRO INT NOT NULL AUTO_INCREMENT
	, IDUSUARIO INT NOT NULL
    , IDTOKEN INT
    , MODULO VARCHAR(200) NOT NULL
    , ACAO VARCHAR(200) NOT NULL
    , DT_REGISTRO DATETIME NOT NULL
    , CONSTRAINT FK_REGISTRO PRIMARY KEY (IDREGISTRO)
    , CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    , CONSTRAINT FK_REGISTRO_TOKEN FOREIGN KEY (IDTOKEN) REFERENCES TOKEN(IDTOKEN)
);
DELIMITER $$
CREATE TRIGGER TR_REGISTRO_BEFORE_INSERT BEFORE INSERT ON REGISTRO FOR EACH ROW 
BEGIN 
    SET NEW.DT_REGISTRO = NOW();
END $$
DELIMITER ;

CREATE VIEW VW_TOKEN AS (
SELECT 
    IDTOKEN
	, IDUSUARIO
    , TOKEN
    , SECRET_KEY
    , DT_CRIACAO
    , DT_EXPIRACAO
    , DESATIVADO
    , DT_DESATIVADO
    , CASE WHEN DT_EXPIRACAO > UTC_TIMESTAMP() AND IFNULL(DESATIVADO, 'N') = 'N' then 'S' ELSE 'N' END ATIVO
FROM
	TOKEN
);

CREATE VIEW VW_USUARIO AS (
SELECT 
    IDUSUARIO
    , NOME
    , EMAIL
    , ATIVO
    , DT_ATIVACAO
    , DESATIVADO
    , DT_DESATIVADO
    , DT_CADASTRO
    , DT_ATUALIZADO
    , (SELECT TOKEN FROM VW_TOKEN T WHERE T.IDUSUARIO = U.IDUSUARIO AND ATIVO = 'S' ORDER BY IDTOKEN DESC LIMIT 1) AS TOKEN_ATIVO
FROM
	USUARIO U
);
